'use strict';
var name = prompt("Is my name Meryl Turner? ");
    console.log(name.toUpperCase());
var live = prompt("Do I live in Portland, Oregon?");
    console.log(live.toUpperCase());
var outdoors = prompt("Do I like the outdoors?");
    console.log(outdoors.toUpperCase());
var coffee = prompt("Do I drink too much coffee?");
    console.log(coffee.toUpperCase());
var coding = prompt("Do I love to code?");
    console.log(coding.toUpperCase());
